version: '3'

vars:
  GO_FILES:
    sh: find . -type f -name '*.go'
  TEST_TIMEOUT: 30s
  PACKAGE_NAME: .
  COVERAGE_FILE: out/coverage.out
  COVERAGE_HTML: out/coverage.html
  COVERAGE_LCOV: out/coverage.lcov
  # PACKAGE_NAME: github.com/difof/errors

tasks:
  default:
    desc: Run tests
    cmd: task test

  tidy:
    desc: Tidy up go.mod and download dependencies
    cmd: go mod tidy

  get:
    desc: Get/update Go dependencies (usage - task get -- package-name)
    cmd: go get -u {{.CLI_ARGS}}

  test:
    desc: Run all tests verbosely
    silent: true
    deps: [check-gotestsum, check-gocov]
    cmd: gotestsum --format testname --hide-summary=output -- -timeout {{.TEST_TIMEOUT}} -count=1 -coverprofile={{.COVERAGE_FILE}} {{.PACKAGE_NAME}} {{.CLI_ARGS}}

  test:file:
    desc: Run tests for specific file (usage - task test:file -- path/to/file_test.go)
    silent: true
    cmd: task test -- -run $(task testfuncs -- {{.CLI_ARGS}} | sed -e ':a' -e 'N' -e '$!ba' -e 's/\n/|/g' -e 's/^/^(/' -e 's/$/)$/')

  test:func:
    desc: Run specific test function (usage - task test:func -- TestFunctionName)
    silent: true
    cmd: |
      task test -- -run ^{{.CLI_ARGS}}$ 

  test:watch:
    desc: Run tests on file changes
    cmd: task test
    sources:
      - '**/*.go'
    method: timestamp
    watch: true

  fmt:
    desc: Format all Go files
    cmd: gofmt -s -w {{.GO_FILES}}

  fmt:check:
    desc: Check if files are formatted correctly
    cmd: gofmt -l {{.GO_FILES}}

  coverage:ci:
    desc: Run tests with coverage and generate reports for CI
    silent: true
    deps: [check-gocov]
    cmds:
      - go test {{.PACKAGE_NAME}} -coverprofile={{.COVERAGE_LCOV}} -coverpkg=./... {{.CLI_ARGS}}
      - |
        if [ "$(uname)" = "Darwin" ]; then
          sed -i '' "s|_$(pwd)|.|g" {{.COVERAGE_LCOV}}
        else
          sed -i "s|_$(pwd)|.|g" {{.COVERAGE_LCOV}}
        fi

  coverage:view:
    desc: Run tests with coverage and generate reports
    silent: true
    aliases: [cov]
    deps: [check-gocov]
    cmds:
      - task test
      - go tool cover -html={{.COVERAGE_FILE}} -o {{.COVERAGE_HTML}}
      - cmd: xdg-open {{.COVERAGE_HTML}}
        platforms: [linux]
      - cmd: open {{.COVERAGE_HTML}}
        platforms: [darwin]
      - cmd: start {{.COVERAGE_HTML}}
        platforms: [windows]

  clean:
    desc: Clean up output folder
    cmd: rm -fr out

  testfuncs:
    desc: Shows a list of all test functions in the given file
    silent: true
    cmd: grep "^func Test" {{.CLI_ARGS}} | awk '{print $2}' | cut -d'(' -f1

  check-gotestsum:
    desc: Check if gotestsum is installed
    internal: true
    silent: true
    cmd: |
      if ! command -v gotestsum >/dev/null 2>&1; then
        echo "Installing gotestsum..."
        go install gotest.tools/gotestsum@latest
      fi

  check-gocov:
    desc: Check if gocov tools are installed
    internal: true
    silent: true
    cmd: |
      if ! command -v gocov >/dev/null 2>&1; then
        echo "Installing gocov..."
        go install github.com/axw/gocov/gocov@latest
      fi

  build:demo:
    desc: Build the formatter demo
    silent: true
    cmd: go build -o out/formatter_demo ./demo/formatter_demo.go

  run:demo:
    desc: Run the formatter demo
    aliases: [demo,run]
    silent: true
    deps: [build:demo]
    cmd: ./out/formatter_demo